### ISSUE TITLE
Fix handling of path list in dbgsysBuildLibName

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk#111] opened 2019-05-24 19:54 UTC
Addressed by ibmruntimes/openj9-openjdk-jdk8#107 for Windows jdk8, but should be fixed for other platforms and other jdk versions.

**Comment by adamfarley** [comment] 2019-06-13 16:11
Todo list: 
- [ ] Understand the problem and the fix.
- [ ] Create a test case.
- [ ] Create a fix.
- [ ] Test the fix.
- [ ] Merge the fix into extensions for jdk head.
- [ ] Create an OpenJDK bug, upload the fix, and email the community for reviews.
- [ ] Merge the fix into upstream OpenJDK and close this issue.

**Comment by adamfarley** [comment] 2019-06-14 15:49
Using this command line (Where TestClass does nothing except print a line to show it ran), I'm unable to reproduce the issue on JDK11 or 12 for OpenJ9. 

```/java -Dsun.boot.library.path=$IGNORE_ME -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo TestClass

(where IGNORE_ME is an environment variable containing 5000 random characters, a separator, and the default sun.boot.library.path, in that order)

I know it's the right command because it reproduces this error on a linux build, but results in correct execution on Windows using a newer j9 jdk8 build.

However, OpenJDK with Hotspot reports the following error for 8, 11, and 12. 

```Error occurred during initialization of VM

Followed by complaining about not being able to find libraries, with the subsequent message related to jdk version and platform.

I assume it's the Hotspot version of this problem, so I still plan to export the fix to OpenJDK 8, 11, and head.

**Comment by adamfarley** [comment] 2019-06-18 16:16
Update: The fix does not solve the hotspot problem, as the testcase fails before we reach the repaired code. Investigating now.

As for extensions, I'm copying the fix into all the different versions just in case. It doesn't damage anything, and it could save our bacon if someone changes the code elsewhere which seems to be preventing this exception from occurring on later versions of OpenJDK.

jdk8 - https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/316
jdk11 - https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/189
jdk12 - https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/58
jdk13 - https://github.com/ibmruntimes/openj9-openjdk-jdk13/pull/1
jdk head - https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/121

**Comment by adamfarley** [comment] 2019-06-19 11:31
I've found the hotspot problem. Working on it.

**Comment by adamfarley** [comment] 2019-06-21 15:01
Update: I found the piece of Hotspot code that should handle this, and I'm rebuilding with debug code to help me understand where and how it's falling over. It *should* work, even when one or more of the paths is too long, and I'm uncertain as to why it doesn't. Will know more soon.

**Comment by adamfarley** [comment] 2019-06-24 12:36
Found the problem. It's the sub-method that actually does the splitting of the string into individual paths. If any of the paths are longer than the maximum length for that OS, then the method returns null *even if the other paths are valid length*. Writing a fix now.

**Comment by adamfarley** [comment] 2019-06-28 15:26
Solved this problem and a handful of other problems in the relevant code. Compiles and passes the tests.

Will tidy up and create an OpenJDK community bug.

**Comment by adamfarley** [comment] 2019-07-01 12:29
Done: https://bugs.openjdk.java.net/browse/JDK-8227021

Will close this issue and monitor the responses upstream.

**Closed by adamfarley** 2019-07-01 12:29 UTC
